<?php

/**
 * Implementation of hook_menu().
 */
function holamundo_menu() {


	$items['hola'] = array(
			'title' => t('Crear Informe de Actividad'),
			'page callback' => 'hola_mundo_callback',

			'access callback'=> TRUE,
			'type' => MENU_LOCAL_TASK,
			
	);


	return $items;
}

function hola_mundo_callback() {

  $user = user_load(1);
  
	$hola = 'hola';
	drupal_set_title('prueba');
	$hola = _get_hola();
	$query = "SELECT * FROM {users} WHERE uid = '%d'";
	$result = db_query($query, $user->uid);
	while ($data = db_fetch_object($result)) {
	  
	  $name = $data->name;
	}
	return 'hola mundo ' . $name;
	
}

function _get_hola() {
  $a = 0;
	
  return $a;
}