<?php

/**
 * Implementación de hook_menu().
 */
function contacto_menu() {
  $items['contacto'] = array (
      'title' => 'Contacto',
      'description' => 'Información de contacto',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('contacto_form'),
      'access callback' => TRUE,
      'type' => MENU_NORMAL_ITEM,
      'file' => 'contacto.pages.inc',
  );
  return $items;
}
